- name: Proxmox Setup
  gather_facts: no
  hosts: proxmox
  remote_user: root
  tasks:
    - name: sshpass
      delegate_to: 127.0.0.1
      ansible.builtin.package:
        name: sshpass
        state: present
    - name: Add ssh keys to hosts
      delegate_to: 127.0.0.1
      command: 'sshpass -f ../ssh-password.txt ssh-copy-id root@{{ inventory_hostname }}'
    - name: Remove pve-enterprise source
      file: path=/etc/apt/sources.list.d/pve-enterprise.list state=absent
    - name: Remove ceph enterprise source
      file: path=/etc/apt/sources.list.d/ceph.list state=absent
    - name: Enable no sub
      ansible.builtin.copy:
        src: ../resources/sources.list
        dest: /etc/apt/sources.list
    - name: Update all host/vm packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        name: "*"
        state: latest
    - name: Update resolvconf if exists (will fail if resolv.conf does not exist in resources. Safe to ignore errors.)
      ansible.builtin.copy:
        src: ../resources/resolv.conf
        dest: /etc/resolv.conf